
before_script:
  - composer self-update
  - composer install --prefer-dist > /dev/null

# PHP 5.5
php:5.5:
  image: bobey/docker-gitlab-ci-runner-php5.5
  script:
    - echo "Running PHPUnit Tests"
    - vendor/bin/phpunit

# PHP 5.6
php:5.6:
  image: bobey/docker-gitlab-ci-runner-php5.6
  script:
    - echo "Running PHPUnit Tests"
    - vendor/bin/phpunit
